organization = "austria-juice"
id = "1"

[logger]
    level = "debug"
    format = "text"

[trigger]
	config = '''
	specification = "@every 5s"
	'''

[actions]
	[actions.imap_action]
		config = '''
			port = ":993"
			domain = "imap.gmail.com"
			username = "ajpipelinetest@gmail.com"
			password = "pleasechangeme"
			fromFilter = "ajpipelinetest@gmail.com"
			subjectFilter = "passphrase"
			'''

	[actions.fileparser_action]
		filetype = "CSV"
		header = false
		delimiter = 59 # unicode decimal for ';'

	[actions.templater_action]
		template = '''
{
  "anfp": "{{.anfp}}",
  "dfp": "{{.dfp}}",
  "bnfp": "{{.bnfp}}",
  "pds": "{{.pds | date "2006-01-02"}}",
  "pde": "{{toDate "20060102" .pde | date "2006-01-02"}}",
  "jds": "{{.jds}}",
  "jde": "{{.jde}}",
  "bbd": "{{.bbd | date "2006-01-02"}}",
  "pc": "{{.pc}}",
  "pl": "{{.pl}}",
  "rmn": "{{.rmn}}",
  "pon": "{{.pon}}",
  "pop": "{{.pop}}"
}
'''
		[actions.templater_action.variables]
			ANFP = "$.col-3"
			DFP = "n/a"
			BNFP = "$.col-6"
			PDS = 1970-01-01
			PDE = "$.col-9"
			JDS = "0"
			JDE = "0"
			BBD = 1970-01-01
			PC = "$.col-7"
			PL = "$.col-8"
			RMN = "n/a"
			PON = "$.col-0"
			POP = "$.col-1"

	[actions.http_action]
		url = "http://localhost:8000/raw/refresco/"
		method = "POST"

	[actions.smtp_action]
		username = "ajpipelinetest@gmail.com"
		password = "pleasechangeme"
		hostname = "smtp.gmail.com"
		port = ":465"
		from = "ajpipelinetest@gmail.com"
		recipients = ["ajpipelinetest@gmail.com"]
